### ISSUE TITLE
Не обновляется аватарка пользователя

### ISSUE THREAD

**Issue by vasyoid** [vasyoid/cremebrulee#11]
#### Описание
При смене пользовательского аватара, на странице пользователя показывается старый аватар.
#### Версия приложения
228.1337 (Android)
#### Шаги для воспроизведения
- Авторизируемся любым пользователем в Android-приложении
- Попадаем на страницу пользователя
- Заходим в настройки
- На странице настроек нажимаем на кнопку "загрузить" под аватаром
- Выбираем изображение
- На странице настроек нажимаем "выйти"
- Попадаем на страницу пользователя
#### Результат
На странице пользователя видим старое изображение

**Comment by MariEliseeva** [comment]
В работе

**Comment by MariEliseeva** [comment]
Решено, тестируется

**Comment by MariEliseeva** [comment]
Протестировано и закрыто
