### ISSUE TITLE
Ошибка в сортировке при отображении списка экскурсий

### ISSUE THREAD

**Issue by MariEliseeva** [vasyoid/cremebrulee#6]
При указании выборгского района для поиска экскурсии первый рекомендованный вариант с более низким рейтингом, чем следующие варианты.

**Comment by vasyoid** [comment]
В работе

**Comment by vasyoid** [comment]
Решено

**Comment by vasyoid** [comment]
Протестировано

**Comment by vasyoid** [comment]
Закрыто
- Исправлены метрики для ранжирования
- Метрике "рейтинг" выставлен более высокий приоритет
- В автотесты на добавлен соответствующий кейс
